### ISSUE TITLE
Merge `proxy_local_port` and `proxy_local_port_with_landing`

### ISSUE THREAD

**Issue by lenormf** [sbrk-org/setup#4]
The differences between the `proxy_local_port` and `proxy_local_port_with_landing` skeleton templates can be handled with a single Jinja2 `if` statement.

This change would page the way for a mono-template of nginx configuration that would include directives based on booleans (or dictionaries) listed in `group_vars/all.yml`. C.f. #2 for an example with the `secure_headers` boolean.

**Comment by aimxhaisse** [comment]
👍
