### ISSUE TITLE
Don't let `certbot` modify the HTTP server's configuration files

### ISSUE THREAD

**Issue by lenormf** [sbrk-org/setup#5]
Certbot includes random things in the HTTP server's configuration file, which triggers my paranoia and additional results in the skeleton templates not being what is actually deployed on the target. E.g. nothing indicates in the `proxy_local_*` templates that SSL will be used, but it ends up being the case *if* the `certbot` task is run.

**Comment by aimxhaisse** [comment]
I'm biased here as I've tried to get it right without using certbot-nginx with different approaches, all being complex/convoluted that required time now and then (like deep-dive 6 months after to fix a change in the certbox CLI).

As we are now using Debian with a vanilla config, and this is using the vanilla package maintained by Debian, I'd rather trust them on this, keeping the nginx config as simple as possible, than having a half-broken certificate every 6 months.

**Comment by lenormf** [comment]
Fair.
